version: '3.9'

services:
  app:
    container_name: sales-gpt
    build:
      context: ./app
      dockerfile: build/Dockerfile
      target: development
    volumes:
      - ./app/server:/app/server
      - backend_node-modules:/app/server/node_modules
    ports:
      - '3001:3001'
    depends_on:
      - database
    env_file:
      - ./app/server/.env
    restart: always

  database:
    container_name: postgres
    image: postgres:latest
    env_file:
      - ./app/server/.env
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    env_file:
      - ./app/server/.env
    ports:
      - '15432:80'
    depends_on:
      - database
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    restart: always

volumes:
  postgres-data:
  backend_node-modules:
  pgadmin-data:
